// Code generated by trpc-go/trpc-cmdline v1.0.9. DO NOT EDIT.
// source: proto/echo.proto

package pb

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// EchoServiceService defines service.
type EchoServiceService interface {
	Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, error)
}

func EchoServiceService_Echo_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &EchoRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(EchoServiceService).Echo(ctx, reqbody.(*EchoRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// EchoServiceServer_ServiceDesc descriptor for server.RegisterService.
var EchoServiceServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "demo.minimaltrpchttpecho.EchoService",
	HandlerType: ((*EchoServiceService)(nil)),
	Methods: []server.Method{
		{
			Name: "/demo.minimaltrpchttpecho.EchoService/Echo",
			Func: EchoServiceService_Echo_Handler,
		},
	},
}

// RegisterEchoServiceService registers service.
func RegisterEchoServiceService(s server.Service, svr EchoServiceService) {
	if err := s.Register(&EchoServiceServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("EchoService register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedEchoService struct{}

func (s *UnimplementedEchoService) Echo(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	return nil, errors.New("rpc Echo of service EchoService is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// EchoServiceClientProxy defines service client proxy
type EchoServiceClientProxy interface {
	Echo(ctx context.Context, req *EchoRequest, opts ...client.Option) (rsp *EchoResponse, err error)
}

type EchoServiceClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewEchoServiceClientProxy = func(opts ...client.Option) EchoServiceClientProxy {
	return &EchoServiceClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *EchoServiceClientProxyImpl) Echo(ctx context.Context, req *EchoRequest, opts ...client.Option) (*EchoResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/demo.minimaltrpchttpecho.EchoService/Echo")
	msg.WithCalleeServiceName(EchoServiceServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("EchoService")
	msg.WithCalleeMethod("Echo")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &EchoResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
