from __future__ import annotations

from typing import Protocol


class KubernetesProvider(Protocol):
    def preflight(self, namespace: str, ingress_class: str | None) -> dict: ...
    def get_deployment_status(self, namespace: str, deployment: str) -> dict: ...
    def get_pods(self, namespace: str, selector: str) -> list[dict]: ...
    def get_events(self, namespace: str) -> list[dict]: ...
    def get_logs(self, namespace: str, deployment: str) -> str: ...
    def discover_endpoint(self, namespace: str, service_name: str, exposure: str) -> str | None: ...
